version: '3'
services:
  christmas-tracker-api-container:
    container_name: app
    restart: always
    image: "balberta/christmas-tracker-api:v1.9"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      SESSION_SECRET: 
      OTP_ENCRYPTION_SECRET: 
      BASIC_ENROLLMENT_ACCESS_KEY: 
      DATABASE_URL: 
      DATABASE_URI_SCHEME: "mongodb+srv://"
      DATABASE_URI_HOST: 
    ports:
      - "3000:3000"
